routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('users', 'UsersController');

Route::resource('items', 'ItemsController');

Route::get('/orders/item/{itemId}', 'OrdersController@orderItem')->name('orderItem');
Route::resource('orders', 'OrdersController');

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $fillable = [
        'name',
        'description',
        'unit_price',
        'stock_quantity',
        'stock_price',
        'minimum_stock'
    ];

    public function order_pending()
    {
        return $this->hasMany('App\Order', 'item_id', 'id')->where('arrived', 0);
    }

    public function order_done()
    {
        return $this->hasMany('App\Order', 'item_id', 'id')->where('arrived', 1);
    }
}

app/Http/Controllers/ItemsController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use Illuminate\Http\Request;

class ItemsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    private $perPage = 5;
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::orderBy('id', 'DESC')->paginate($this->perPage);

        $returns['items'] = $items;

        return view('pages.items.index', $returns);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.items.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $entryData = [];
        $data = $request->all();

        $message = [
            'name.required' => "Campo Nome é obrigatório.",
            'name.max' => "Campo Nome deve conter, no máximo, 100 caracteres.",
            'unit_price.required' => "Campo de Preço é obrigatório.",
            'stock_quantity.required' => "Campo de Quantidade é obrigatório"
        ];

        $this->validate($request, [
            'name' => "required|max:100",
            'description' => "required|max:150",
            'unit_price' => "required",
            'stock_quantity' => "required",
        ], $message);

        $entryData['name'] = $data['name'];
        $entryData['description'] = $data['description'];
        $entryData['unit_price'] = $data['unit_price'];
        $entryData['stock_quantity'] = $data['stock_quantity'];
        $entryData['stock_price'] = $data['stock_quantity'] * $data['unit_price'];
        $entryData['minimum_stock'] = $data['stock_quantity'];

        $item = Item::create($entryData);
        if ($item) {
            return redirect()
                ->route('items.index')
            ->with('message', 'Item criado com sucesso!');
        }

        return redirect()
            ->route('items.create')
        ->with('message', 'Ocorreu um erro ao criar o Item. Verifique as informações e tente novamente. Caso o erro persista entre em contato com o suporte.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = Item::where('id', $id)->first();

        if ($item) {
            $returns['item'] = $item;
            return view('pages.items.show', $returns);
        }

        return redirect()
            ->route('items.index')
        ->with('message', 'Item não encontrado. Verifique se este existe e tente novamente. Caso o erro persista entre em contato com o suporte.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $item = Item::where('id', $id)->first();

        if ($item) {
            $returns['item'] = $item;
            return view('pages.items.edit', $returns);
        }

        return redirect()
            ->route('items.index')
        ->with('message', 'Item não pode ser encontrado. Verifique se este existe e tente novamente. Caso o erro persista entre em contato com o suporte.');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $updateData = [];
        $data = $request->all();

        $updateData['name'] = $data['name'];
        $updateData['description'] = $data['description'];
        $updateData['unit_price'] = $data['unit_price'];
        $updateData['minimum_stock'] = $data['minimum_stock'];

        $item = Item::where('id', $id)->first();

        if ($item) {
            $quantity = $item->stock_quantity;
            $stockPrice = $updateData['unit_price'] * $quantity;
            $updateData['stock_price'] = $stockPrice;

            $result = $item->fill($updateData)->save();

            if ($result) {
                return redirect()
                    ->route('items.index')
                ->with('message', 'Item atualizado com sucesso!');
            }

            return redirect()
                ->route('items.edit', $id)
            ->with('message', 'Ocorreu um erro ao atualizar o Item. Verifique as informações e tente novamente. Caso o erro persista entre em contato com o suporte');
        }

        return redirect()
            ->route('items.index')
        ->with('message', 'Item não encontrado. Verifique se este existe e tente novamente. Caso o erro persista entre em contato com o suporte');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $item = Item::where('id', $id)->first();

        if ($item) {
            $expected = $item->delete();

            if ($expected) {
                return redirect()
                    ->route('items.index')
                ->with('message', 'Item deletado com sucesso.');
            }

            return redirect()
                ->route('items.index')
            ->with('message', 'Ocorreu um erro ao deletar o Item. Verifique as informações e tente novamente. Caso o erro persista entre em contato com o suporte.');
        }

        return redirect()
            ->route('items.index')
        ->with('message', 'Item não encontrado. Verifique se este existe e tente novamente. Caso o erro persista entre em contato com o suporte.');
    }
}

resources/views/pages/items/_create-form.blade.php
<div class="form-wrapper">
    <form class="form-default"
        action="{{ route('items.store') }}"
        method="POST">
        @csrf
        <div class="form-default__item-wrapper">
            <label class="form-default__item-wrapper__label">
                Nome do Item
            </label>
            <input type="text" name="name" required
                class="form-default__item-wrapper__input"
                value="{{ old('name') }}">
        </div>

        <div class="form-default__item-wrapper">
            <label class="form-default__item-wrapper__label">
                Descrição de Item
            </label>
            <input type="text" name="description" required
                class="form-default__item-wrapper__input"
                value="{{ old('description') }}">
        </div>

        <div class="form-default__item-wrapper">
            <label class="form-default__item-wrapper__label">
                Preço Unitário (em R$)
            </label>
            <input type="number" name="unit_price" step="0.01" required
                class="form-default__item-wrapper__input"
                value="{{ old('unit_price') }}">
        </div>

        <div class="form-default__item-wrapper">
            <label class="form-default__item-wrapper__label">
                Estoque de Item
            </label>
            <input type="number" name="stock_quantity" step="1" required
                class="form-default__item-wrapper__input"
                value="{{ old('stock_quantity') }}">
        </div>

        <div class="form-default__item-wrapper">
            <button type="submit" class="form-default__item-wrapper__button">
                Salvar Edições
            </button>
        </div>
    </form>
</div>

resources/views/pages/items/_edit-form.blade.php
<div class="form-wrapper">
    <form class="form-default"
        action="{{ route('items.update', $item->id) }}"
        method="POST">
        @csrf
        @method('PUT')
        <div class="form-default__item-wrapper">
            <label class="form-default__item-wrapper__label">
                Nome do Item
            </label>
            <input type="text" name="name"
                class="form-default__item-wrapper__input"
                value="{{ (isset($item) && $item) ? $item->name : '' }}">
        </div>

        <div class="form-default__item-wrapper">
            <label class="form-default__item-wrapper__label">
                Descrição de Item
            </label>
            <input type="text" name="description"
                class="form-default__item-wrapper__input"
                value="{{ (isset($item) && $item) ? $item->description : '' }}">
        </div>

        <div class="form-default__item-wrapper">
            <label class="form-default__item-wrapper__label">
                Preço Unitário (em R$)
            </label>
            <input type="number" name="unit_price" step="0.01"
                class="form-default__item-wrapper__input"
                value="{{ (isset($item) && $item) ? $item->unit_price : '' }}">
        </div>

        <div class="form-default__item-wrapper">
            <label class="form-default__item-wrapper__label">
                Estoque Mínimo de Item
            </label>
            <input type="number" name="minimum_stock"
                class="form-default__item-wrapper__input"
                value="{{ (isset($item) && $item) ? $item->minimum_stock : '' }}">
        </div>

        <div class="form-default__item-wrapper">
            <button type="submit" class="form-default__item-wrapper__button">
                Salvar Edições
            </button>
        </div>
    </form>
</div>

resources/views/pages/items/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="canvas-header">
        Estoque : : Adicionar Novo Item
    </div>

    @include('pages.items._create-form')
@endsection

resources/views/pages/items/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="canvas-header">
        Estoque : : Editar Informações de Item
    </div>

    @include('pages.items._edit-form')
@endsection

resources/views/pages/items/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="canvas-header space-between">
        Estoque : : Listagem de Estoque

        <a href="{{ route('items.create') }}" title="Adicionar novo Item">
            <svg height="24" viewBox="0 0 24 24" width="24">
                <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm5 11h-4v4h-2v-4H7v-2h4V7h2v4h4v2z" fill="#FFF"/>
            </svg>

        </a>
    </div>

    <table class="table-default">
            <thead>
                <tr>
                    <th scope="col">
                        #ID
                    </th>
                    <th scope="col">
                        Nome
                    </th>
                    <th scope="col">
                        Descrição
                    </th>
                    <th scope="col">
                        Preço Unitário
                    </th>
                    <th scope="col">
                        Quantidade em Estoque
                    </th>
                    <th scope="col">
                        Estoque Mínimo
                    </th>
                    <th scope="col">
                        Fazer Pedido
                    </th>
                    <th scope="col">
                        Preço de Estoque por Item
                    </th>
                </tr>
            </thead>
            <tbody>
                @forelse($items as $item)
                    <tr>
                        <td scope="row">
                            {{ $item->id }}
                        </td>
                        <td>
                            <a class="table-link"
                                href="{{ route('items.edit', $item->id) }}" title="Editar Item">
                                {{ $item->name }}
                            </a>
                        </td>
                        <td>
                            <a class="table-link"
                                href="{{ route('items.edit', $item->id) }}" title="Editar Item">
                                {{ $item->description }}
                            </a>
                        </td>
                        <td>
                            R$ {{ number_format($item->unit_price, 2, ',', '.') }}
                        </td>
                        <td>
                            {{ $item->stock_quantity }}
                        </td>
                        <td>
                            {{ $item->minimum_stock }}
                        </td>
                        <td style="text-align: center">
                            @if ($item->stock_quantity < $item->minimum_stock)
                                    <a href="{{ route('orderItem', ['itemId' => $item->id]) }}" title="Fazer Pedido de Item">
                                        <svg height="24" viewBox="0 0 24 24" width="24">
                                            <path d="M20 2H4c-1.1 0-1.99.9-1.99 2L2 22l4-4h14c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-7 9h-2V5h2v6zm0 4h-2v-2h2v2z" fill="#e3a621"/>
                                        </svg>
                                    </a>
                            @else
                                <svg height="24" viewBox="0 0 24 24" width="24">
                                    <path d="M1 21h4V9H1v12zm22-11c0-1.1-.9-2-2-2h-6.31l.95-4.57.03-.32c0-.41-.17-.79-.44-1.06L14.17 1 7.59 7.59C7.22 7.95 7 8.45 7 9v10c0 1.1.9 2 2 2h9c.83 0 1.54-.5 1.84-1.22l3.02-7.05c.09-.23.14-.47.14-.73v-2z" fill="#18741a"/>
                                </svg>
                            @endif
                        </td>
                        <td>
                            R$ {{ number_format($item->stock_price, 2, ',', '.') }}
                        </td>
                    </tr>
                @empty
                    <tr class="empty">
                        <td colspan="8">
                            Nenhum Item Cadastrado
                        </td>
                    </tr>
                @endforelse
            </tbody>
        </table>

        {{ method_exists($items, 'links') ? $items->links() : '' }}
@endsection