routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('users', 'UsersController');

Route::resource('items', 'ItemsController');

Route::get('/orders/item/{itemId}', 'OrdersController@orderItem')->name('orderItem');
Route::resource('orders', 'OrdersController');

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Auth;
use Illuminate\Http\Request;

class UsersController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $returns = [];
        $user = User::where('id', $id)->first();

        if ($user) {
            if ($user->id === Auth::user()->id) {
                $returns['user'] = $user;

                return view('pages.users.edit', $returns);
            }

            return redirect()
                ->route('home')
            ->with('message', 'Ação não permitida.');
        }

        return redirect()
            ->route('home')
        ->with('message', 'Usuário não encontrado. Certifique-se de que este existe e tente novamente. Caso o problema persista entre em contato com o suporte.');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $user = User::where('id', $id)->first();

        if ($user) {
            if ($user->id === Auth::user()->id) {
                if (isset($data['name']) && isset($data['email'])) {
                    $result = $user->fill($data)->save();

                    if ($result) {
                        return redirect()
                            ->route('users.edit', $user->id)
                        ->with('message', 'Dados editados com sucesso!');
                    }

                    return redirect()
                        ->route('users.edit', $user->id)
                    ->with('message', 'Erro ao atualizar dados. Certifique-se de que os dados estão corretos e tente novamente. Caso o erro persista entre em contato com o suporte.');
                }

                return redirect()
                    ->route('users.edit', $id)
                ->with('message', 'Ação não permitida.');
            }
        }

        return redirect()
            ->route('home')
        ->with('message', 'Usuário não encontrado. Certifique-se de que este existe e tente novamente. Caso o erro persista entre em contato com o suporte.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/users/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="canvas-header">
        Editar dados : : {{ $user->name }}
    </div>

    @include('pages.users.form')
@endsection

resources/views/pages/users/form.blade.php
<div class="form-wrapper">
    <form class="form-default"
        action="{{ route('users.update', $user->id) }}"
        method="POST">
        @csrf
        @method('PUT')
        <div class="form-default__item-wrapper">
            <label class="form-default__item-wrapper__label">
                Nome de Usuário
            </label>
            <input type="text" name="name"
                class="form-default__item-wrapper__input"
                value="{{ (isset($user) && $user) ? $user->name : '' }}">
        </div>

        <div class="form-default__item-wrapper">
            <label class="form-default__item-wrapper__label">
                E-mail
            </label>
            <input type="email" name="email"
                class="form-default__item-wrapper__input"
                value="{{ (isset($user) && $user) ? $user->email : '' }}">
        </div>

        <div class="form-default__item-wrapper">
            <button type="submit" class="form-default__item-wrapper__button">
                Salvar Edições
            </button>
        </div>
    </form>
</div>